---
- hosts: all
  become: yes

  roles:
    - smokeping
    - icinga2

  tasks:
    - name: "Ensure mDNS components are removed"
      apt: state=absent name="{{ item }}"
      with_items:
        - libnss-mdns
        - avahi-daemon
        - salt-minion
