---
- hosts: all
  sudo: yes

  roles:
    - smokeping
    - icinga2

  tasks:
    - apt: state=absent name="{{ item }}"
      with_items:
        - libnss-mdns
        - avahi-daemon
        - salt-minion

    - shell: apt-get autoremove -y
